variables:
  PROJECT_GROUP: waterchat
  PROJECT_NAME: messages

stages:
  # - test
  - build
  - deploy

build:
  stage: build
  script:
    - docker pull 10.0.0.75:5000/$PROJECT_GROUP/$PROJECT_NAME
    - docker build -t $PROJECT_GROUP/$PROJECT_NAME:latest -t $PROJECT_GROUP/$PROJECT_NAME:$CI_JOB_ID . 
    - docker push 10.0.0.75:5000/$PROJECT_GROUP/$PROJECT_NAME
  tags:
    - shell

# test:
#   image: node:8-alpine
#   stage: test
#   script:
#     - npm install
#     - npm test
#   tags:
#     - docker

trigger_build:
  stage: deploy
  script:
    - docker service rm ${PROJECT_GROUP}_${PROJECT_NAME}
    - "curl -X POST -F token=57ac25fd7c00d7282208c92486b851 -F ref=master https://office.cap3.de:52203/api/v4/projects/286/trigger/pipeline"
  tags:
    - shell